<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.fiap.bank</groupId>
        <artifactId>fiap-bank-atm</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>domain</artifactId>
    <packaging>jar</packaging>
    <name>fiap-bank-atm-domain</name>
    <description>Camada de Domínio: entidades, objetos de valor, exceções de negócio e contratos de repositório.</description>

    <!--
        REGRA ARQUITETURAL: o núcleo do domínio é o centro da aplicação e
        NÃO possui NENHUMA dependência de outros módulos ou de frameworks.
        Apenas a biblioteca padrão do Java (Java SE).
    -->
    <dependencies>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
        </dependency>
    </dependencies>
</project>
